import { StyleSheet } from 'react-native';

import { AppColors } from '../../theme/palette';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    flex: 1,
    padding: 18,
    paddingBottom: 0,
    gap: 14,
  },
  fixedHeaderSection: {
    gap: 14,
  },
  timelineScrollView: {
    flex: 1,
  },
  timelineScrollContent: {
    paddingBottom: 80,
  },
  summaryCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 24,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  summaryLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  summaryValue: {
    marginTop: 4,
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '800',
  },
  summaryValueWrap: {
    flex: 1,
    minWidth: 0,
  },
  summaryRingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ scale: 0.82 }],
    flexShrink: 0,
  },
  summaryMeta: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  summaryMetaWrap: {
    flex: 1,
    alignItems: 'flex-end',
    gap: 4,
    minWidth: 0,
  },
  summaryMetaSecondary: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dateArrow: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.actionSurface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  dateArrowDisabled: {
    opacity: 0.55,
  },
  datePill: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 26,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  datePillTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  dateIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionSurface,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateTextWrap: {
    flex: 1,
    gap: 2,
  },
  dateEyebrow: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  dateLabel: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  dateSubLabel: {
    marginTop: 4,
    color: colors.textMuted,
    fontSize: 13,
  },
  timelineCard: {
    backgroundColor: colors.surface,
    borderRadius: 30,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 0,
  },
  emptyDayCard: {
    marginBottom: 12,
    borderRadius: 20,
    padding: 14,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    gap: 6,
  },
  emptyDayTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  emptyDayText: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  timelineRow: {
    position: 'relative',
    flexDirection: 'row',
    minHeight: 64,
    alignItems: 'flex-start',
  },
  hourColumn: {
    width: 56,
    minHeight: 28,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  hourBadge: {
    minWidth: 54,
    paddingLeft: 2,
    paddingRight: 5,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: colors.actionSurface,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  hourBadgeContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  hourBadgeActive: {
    backgroundColor: colors.surfaceMuted,
  },
  timelineContentColumn: {
    flex: 1,
    paddingBottom: 8,
    paddingLeft: 12,
  },
  timelineContentColumnCreateActive: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.actionBorder,
  },
  timelineContentColumnMoveActive: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.actionBorder,
  },
  timelineHeaderRow: {
    minHeight: 28,
    justifyContent: 'center',
  },
  timelineLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 27,
    width: 2,
    backgroundColor: colors.actionBorder,
  },
  hourMarker: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    flexShrink: 0,
  },
  hourCurrentDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.accent,
  },
  sessionList: {
    marginTop: 6,
    marginLeft: -2,
    gap: 8,
  },
  sessionSelectableWrap: {
    position: 'relative',
  },
  sessionSelectionIndicator: {
    position: 'absolute',
    left: -49,
    top: '50%',
    width: 22,
    height: 22,
    marginTop: -11,
    borderRadius: 11,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
  },
  sessionSelectionIndicatorActive: {
    backgroundColor: colors.textPrimary,
    borderColor: colors.textPrimary,
  },
  sessionCard: {
    backgroundColor: colors.actionSurface,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sessionCardSelectable: {
    paddingLeft: 16,
  },
  sessionCardSelected: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.textPrimary,
    shadowColor: colors.shadow,
    shadowOpacity: 0.18,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 6,
  },
  sessionCardDragging: {
    opacity: 0.45,
  },
  sessionDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.textPrimary,
  },
  sessionTextWrap: {
    gap: 4,
    flex: 1,
    minWidth: 0,
  },
  sessionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  sessionMeta: {
    color: colors.textMuted,
    fontSize: 13,
  },
  sessionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  sessionEditButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sessionTimePill: {
    minHeight: 28,
    borderRadius: 14,
    paddingHorizontal: 10,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sessionTimePillText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  sessionDeleteButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.destructive,
    borderWidth: 1,
    borderColor: colors.destructiveBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyHourWrap: {
    height: 26,
    justifyContent: 'center',
    marginLeft: -2,
  },
  hourActionButton: {
    width: 30,
    height: 30,
    marginLeft: -2,
    borderRadius: 15,
    backgroundColor: colors.actionSurface,
    borderWidth: 2,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hourActionButtonActive: {
    backgroundColor: colors.surfaceMuted,
  },
  hourActionSpacer: {
    width: 30,
    height: 30,
    marginLeft: -2,
  },
  emptyHourDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.textMuted,
  },
  adjustRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  adjustButton: {
    flexGrow: 1,
    minWidth: '22%',
    backgroundColor: colors.actionSurface,
    borderRadius: 18,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.actionBorder,
  },
  adjustButtonText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  quickWrap: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  quickChip: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: colors.actionSurface,
    alignItems: 'center',
  },
  quickChipActive: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.actionBorder,
  },
  quickChipText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  quickChipTextActive: {
    color: colors.textPrimary,
  },
  modalActionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 24,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  saveButtonWrap: {
    flex: 1.35,
  },
  saveButton: {
    borderRadius: 24,
    minHeight: 58,
    paddingVertical: 18,
    backgroundColor: colors.actionSurface,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  saveButtonText: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: '800',
  },
  selectionBarWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.background,
    zIndex: 50,
    elevation: 12,
  },
  selectionBar: {
    minHeight: 58,
    // borderRadius: 0,
    paddingHorizontal: 16,
    backgroundColor: colors.actionSurface,
    // borderWidth: 1,
    borderColor: colors.actionBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    shadowColor: colors.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  selectionBarText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
    flex: 1,
  },
  selectionBarActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
  },
  selectionSecondaryButton: {
    minHeight: 40,
    borderRadius: 16,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  selectionSecondaryButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  selectionPrimaryButton: {
    minHeight: 40,
    borderRadius: 16,
    backgroundColor: colors.destructive,
    borderWidth: 1,
    borderColor: colors.destructiveBorder,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
  },
  selectionPrimaryButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  messageStackWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 12,
    zIndex: 85,
    gap: 10,
  },
  undoCard: {
    minHeight: 56,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  undoText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  undoButton: {
    borderRadius: 999,
    backgroundColor: colors.actionSurface,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  undoButtonText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  toastCard: {
    minHeight: 52,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: colors.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 16,
  },
  toastCardWarning: {
    borderColor: colors.warningBorder,
    backgroundColor: colors.warning,
  },
  toastText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  modalToastWrap: {
    marginTop: -2,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  modalDismissArea: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 30,
    borderTopWidth: 1,
    borderColor: colors.actionBorder,
    gap: 18,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.textMuted,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '800',
    textAlign: 'center',
  },
  modalSubtitle: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  modalCounterCard: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    width: '100%',
    gap: 6,
  },
  timePickerRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
    marginTop: 10,
    width: '100%',
  },
  timePickerField: {
    flex: 1,
    minHeight: 92,
    borderRadius: 18,
    backgroundColor: colors.actionSurface,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  timePickerLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  timeStepperRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  timeAdjustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    marginTop: 10,
    width: '100%',
  },
  timeAdjustButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.actionSurface,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeAdjustCenter: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    gap: 2,
  },
  timeAdjustLabel: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
    width: '100%',
  },
  timeAdjustMeta: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  modalCounterInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 3,
  },
  modalCounterInput: {
    width: 72,
    color: colors.textPrimary,
    fontSize: 34,
    fontWeight: '800',
    textAlign: 'right',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  modalCounterUnit: {
    color: colors.textSecondary,
    fontSize: 34,
    fontWeight: '800',
  },
  modalCounterValue: {
    color: colors.textPrimary,
    fontSize: 34,
    fontWeight: '800',
  },
  modalCounterMeta: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  dialogOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  dialogDismissArea: {
    ...StyleSheet.absoluteFillObject,
  },
  dialogCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 14,
    shadowColor: colors.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 20,
  },
  dialogIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  dialogText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  dialogSecondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogSecondaryText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  dialogPrimaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: colors.actionSurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogPrimaryText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
});
