import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#09090b',
  },
  content: {
    padding: 20,
    paddingBottom: 116,
    gap: 20,
  },
  summaryCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#111113',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#27272a',
    gap: 12,
  },
  summaryLabel: {
    color: '#a1a1aa',
    fontSize: 13,
    fontWeight: '600',
  },
  summaryValue: {
    marginTop: 6,
    color: '#f8fafc',
    fontSize: 28,
    fontWeight: '800',
  },
  summaryMeta: {
    color: '#d4d4d8',
    fontSize: 14,
    fontWeight: '700',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dateArrow: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#323232',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#27272a',
  },
  dateArrowDisabled: {
    opacity: 0.55,
  },
  datePill: {
    flex: 1,
    backgroundColor: '#111113',
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#27272a',
  },
  dateLabel: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
  },
  dateSubLabel: {
    marginTop: 4,
    color: '#a1a1aa',
    fontSize: 13,
  },
  timelineCard: {
    backgroundColor: '#111113',
    borderRadius: 30,
    padding: 14,
    borderWidth: 1,
    borderColor: '#27272a',
    gap: 0,
  },
  timelineRow: {
    position: 'relative',
    flexDirection: 'row',
    minHeight: 64,
    alignItems: 'flex-start',
  },
  hourColumn: {
    width: 56,
    minHeight: 28,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  hourBadge: {
    minWidth: 54,
    paddingLeft: 2,
    paddingRight: 5,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: '#323232',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  timelineContentColumn: {
    flex: 1,
    paddingBottom: 8,
    paddingLeft: 18,
  },
  timelineHeaderRow: {
    minHeight: 28,
    justifyContent: 'center',
  },
  timelineLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 27,
    width: 2,
    backgroundColor: '#3f3f46',
  },
  hourMarker: {
    color: '#fafafa',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  sessionList: {
    marginTop: 6,
    marginLeft: -2,
    gap: 8,
  },
  sessionCard: {
    backgroundColor: '#323232',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#4a4a4a',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sessionDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#f5f5f5',
  },
  sessionTextWrap: {
    gap: 4,
    flex: 1,
  },
  sessionTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  sessionMeta: {
    color: '#a1a1aa',
    fontSize: 13,
  },
  sessionDeleteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#5a1f24',
    borderWidth: 1,
    borderColor: '#7f1d1d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyHourWrap: {
    height: 26,
    justifyContent: 'center',
    marginLeft: -2,
  },
  hourActionButton: {
    width: 22,
    height: 22,
    marginLeft: -2,
    borderRadius: 11,
    backgroundColor: '#323232',
    borderWidth: 1,
    borderColor: '#3f3f46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hourActionSpacer: {
    width: 22,
    height: 22,
    marginLeft: -2,
  },
  emptyHourDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#52525b',
  },
  adjustRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  adjustButton: {
    flexGrow: 1,
    minWidth: '47%',
    backgroundColor: '#323232',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#27272a',
  },
  adjustButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  quickWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#3f3f46',
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#323232',
  },
  quickChipActive: {
    backgroundColor: '#323232',
    borderColor: '#52525b',
  },
  quickChipText: {
    color: '#fafafa',
    fontWeight: '700',
  },
  quickChipTextActive: {
    color: '#fafafa',
  },
  modalActionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 24,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#3f3f46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: '#fafafa',
    fontSize: 16,
    fontWeight: '800',
  },
  saveButtonWrap: {
    flex: 1.35,
  },
  saveButton: {
    borderRadius: 24,
    minHeight: 58,
    paddingVertical: 18,
    backgroundColor: '#323232',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  saveButtonText: {
    color: '#fafafa',
    fontSize: 17,
    fontWeight: '800',
  },
  floatingBarWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 4,
    backgroundColor: '#09090b',
    zIndex: 50,
    elevation: 12,
  },
  floatingBar: {
    minHeight: 54,
    borderRadius: 22,
    paddingHorizontal: 16,
    backgroundColor: '#323232',
    borderWidth: 1,
    borderColor: '#3f3f46',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  floatingBarText: {
    color: '#fafafa',
    fontSize: 15,
    fontWeight: '800',
  },
  toastWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 70,
    zIndex: 80,
    elevation: 16,
  },
  toastCard: {
    minHeight: 52,
    borderRadius: 20,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#3f3f46',
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 16,
  },
    toastCardWarning: {
      borderColor: '#7c5a1d',
      backgroundColor: '#21180a',
    },
  toastText: {
    color: '#fafafa',
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  modalToastWrap: {
    marginTop: -2,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  modalDismissArea: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: '#111113',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 30,
    borderTopWidth: 1,
    borderColor: '#3f3f46',
    gap: 18,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#52525b',
  },
  modalTitle: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '800',
  },
  modalSubtitle: {
    color: '#a1a1aa',
    fontSize: 14,
    lineHeight: 20,
  },
  modalCounterCard: {
    backgroundColor: '#18181b',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#3f3f46',
    alignItems: 'center',
    gap: 6,
  },
  modalCounterInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 3,
  },
  modalCounterInput: {
    width: 72,
    color: '#f8fafc',
    fontSize: 34,
    fontWeight: '800',
    textAlign: 'right',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  modalCounterUnit: {
    color: '#d4d4d8',
    fontSize: 34,
    fontWeight: '800',
  },
  modalCounterValue: {
    color: '#f8fafc',
    fontSize: 34,
    fontWeight: '800',
  },
  modalCounterMeta: {
    color: '#a1a1aa',
    fontSize: 14,
    fontWeight: '600',
  },
  dialogOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.58)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  dialogDismissArea: {
    ...StyleSheet.absoluteFillObject,
  },
  dialogCard: {
    backgroundColor: '#111113',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#3f3f46',
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 14,
    shadowColor: '#000',
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 20,
  },
  dialogIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#232328',
    borderWidth: 1,
    borderColor: '#3f3f46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogTitle: {
    color: '#fafafa',
    fontSize: 20,
    fontWeight: '800',
  },
  dialogText: {
    color: '#a1a1aa',
    fontSize: 14,
    lineHeight: 20,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  dialogSecondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: '#18181b',
    borderWidth: 1,
    borderColor: '#3f3f46',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogSecondaryText: {
    color: '#fafafa',
    fontSize: 15,
    fontWeight: '700',
  },
  dialogPrimaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: '#323232',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogPrimaryText: {
    color: '#fafafa',
    fontSize: 15,
    fontWeight: '800',
  },
});
