import { StyleSheet } from 'react-native';

import { AppColors } from '../../theme/palette';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    padding: 20,
    paddingBottom: 116,
    gap: 20,
  },
  summaryCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  summaryLabel: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  summaryValue: {
    marginTop: 6,
    color: colors.textPrimary,
    fontSize: 28,
    fontWeight: '800',
  },
  summaryMeta: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '700',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dateArrow: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.actionSurface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  dateArrowDisabled: {
    opacity: 0.55,
  },
  datePill: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dateLabel: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  dateSubLabel: {
    marginTop: 4,
    color: colors.textMuted,
    fontSize: 13,
  },
  timelineCard: {
    backgroundColor: colors.surface,
    borderRadius: 30,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 0,
  },
  timelineRow: {
    position: 'relative',
    flexDirection: 'row',
    minHeight: 64,
    alignItems: 'flex-start',
  },
  hourColumn: {
    width: 56,
    minHeight: 28,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  hourBadge: {
    minWidth: 54,
    paddingLeft: 2,
    paddingRight: 5,
    paddingVertical: 4,
    borderRadius: 14,
    backgroundColor: colors.actionSurface,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  hourBadgeActive: {
    backgroundColor: colors.surfaceMuted,
  },
  timelineContentColumn: {
    flex: 1,
    paddingBottom: 8,
    paddingLeft: 18,
  },
  timelineContentColumnCreateActive: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.actionBorder,
  },
  timelineContentColumnMoveActive: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.actionBorder,
  },
  timelineHeaderRow: {
    minHeight: 28,
    justifyContent: 'center',
  },
  timelineLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 27,
    width: 2,
    backgroundColor: colors.actionBorder,
  },
  hourMarker: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  sessionList: {
    marginTop: 6,
    marginLeft: -2,
    gap: 8,
  },
  sessionCard: {
    backgroundColor: colors.actionSurface,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sessionCardDragging: {
    opacity: 0.45,
  },
  sessionDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.textPrimary,
  },
  sessionTextWrap: {
    gap: 4,
    flex: 1,
  },
  sessionTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  sessionMeta: {
    color: colors.textMuted,
    fontSize: 13,
  },
  sessionDeleteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.destructive,
    borderWidth: 1,
    borderColor: colors.destructiveBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyHourWrap: {
    height: 26,
    justifyContent: 'center',
    marginLeft: -2,
  },
  hourActionButton: {
    width: 22,
    height: 22,
    marginLeft: -2,
    borderRadius: 11,
    backgroundColor: colors.actionSurface,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hourActionButtonActive: {
    backgroundColor: colors.surfaceMuted,
  },
  hourActionSpacer: {
    width: 22,
    height: 22,
    marginLeft: -2,
  },
  emptyHourDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.textMuted,
  },
  adjustRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  adjustButton: {
    flexGrow: 1,
    minWidth: '47%',
    backgroundColor: colors.actionSurface,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  adjustButtonText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  quickWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: colors.actionSurface,
  },
  quickChipActive: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.actionBorder,
  },
  quickChipText: {
    color: colors.textPrimary,
    fontWeight: '700',
  },
  quickChipTextActive: {
    color: colors.textPrimary,
  },
  modalActionRow: {
    flexDirection: 'row',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    minHeight: 58,
    borderRadius: 24,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  saveButtonWrap: {
    flex: 1.35,
  },
  saveButton: {
    borderRadius: 24,
    minHeight: 58,
    paddingVertical: 18,
    backgroundColor: colors.actionSurface,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  saveButtonText: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: '800',
  },
  floatingBarWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 4,
    backgroundColor: colors.background,
    zIndex: 50,
    elevation: 12,
  },
  floatingBar: {
    minHeight: 54,
    borderRadius: 22,
    paddingHorizontal: 16,
    backgroundColor: colors.actionSurface,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: colors.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  floatingBarText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
  undoWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 78,
    zIndex: 85,
  },
  undoCard: {
    minHeight: 56,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  undoText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  undoButton: {
    borderRadius: 999,
    backgroundColor: colors.actionSurface,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  undoButtonText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  toastWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 70,
    zIndex: 80,
    elevation: 16,
  },
  toastCard: {
    minHeight: 52,
    borderRadius: 20,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: colors.shadow,
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 16,
  },
  toastCardWarning: {
    borderColor: colors.warningBorder,
    backgroundColor: colors.warning,
  },
  toastText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  modalToastWrap: {
    marginTop: -2,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  modalDismissArea: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 30,
    borderTopWidth: 1,
    borderColor: colors.actionBorder,
    gap: 18,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.textMuted,
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: '800',
  },
  modalSubtitle: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  modalCounterCard: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    gap: 6,
  },
  timeAdjustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 10,
  },
  timeAdjustButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.actionSurface,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeAdjustCenter: {
    minWidth: 90,
    alignItems: 'center',
    gap: 2,
  },
  timeAdjustLabel: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '800',
  },
  timeAdjustMeta: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  modalCounterInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 3,
  },
  modalCounterInput: {
    width: 72,
    color: colors.textPrimary,
    fontSize: 34,
    fontWeight: '800',
    textAlign: 'right',
    paddingVertical: 0,
    paddingHorizontal: 0,
  },
  modalCounterUnit: {
    color: colors.textSecondary,
    fontSize: 34,
    fontWeight: '800',
  },
  modalCounterValue: {
    color: colors.textPrimary,
    fontSize: 34,
    fontWeight: '800',
  },
  modalCounterMeta: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  dialogOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  dialogDismissArea: {
    ...StyleSheet.absoluteFillObject,
  },
  dialogCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 14,
    shadowColor: colors.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 20,
  },
  dialogIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  dialogText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  dialogActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 2,
  },
  dialogSecondaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.actionBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogSecondaryText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  dialogPrimaryButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 18,
    backgroundColor: colors.actionSurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dialogPrimaryText: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '800',
  },
});
