import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#09090b',
  },
  content: {
    padding: 20,
    paddingBottom: 132,
    gap: 20,
  },
  summaryCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#111113',
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: '#27272a',
    gap: 12,
  },
  summaryLabel: {
    color: '#a1a1aa',
    fontSize: 13,
    fontWeight: '600',
  },
  summaryValue: {
    marginTop: 6,
    color: '#f8fafc',
    fontSize: 28,
    fontWeight: '800',
  },
  summaryMeta: {
    color: '#d4d4d8',
    fontSize: 14,
    fontWeight: '700',
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dateArrow: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#111113',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#27272a',
  },
  datePill: {
    flex: 1,
    backgroundColor: '#111113',
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderWidth: 1,
    borderColor: '#27272a',
  },
  dateLabel: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
  },
  dateSubLabel: {
    marginTop: 4,
    color: '#a1a1aa',
    fontSize: 13,
  },
  timelineCard: {
    backgroundColor: '#111113',
    borderRadius: 30,
    padding: 14,
    borderWidth: 1,
    borderColor: '#27272a',
    gap: 2,
  },
  timelineRow: {
    flexDirection: 'row',
    minHeight: 64,
  },
  hourColumn: {
    width: 56,
    paddingTop: 4,
  },
  timelineContentColumn: {
    flex: 1,
    paddingBottom: 8,
    paddingLeft: 12,
  },
  timelineLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 5,
    width: 2,
    backgroundColor: '#3f3f46',
  },
  hourMarker: {
    color: '#a1a1aa',
    fontSize: 13,
    fontWeight: '700',
  },
  sessionCard: {
    marginBottom: 8,
    marginLeft: 14,
    backgroundColor: '#18181b',
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#3f3f46',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sessionDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#f5f5f5',
  },
  sessionTextWrap: {
    gap: 4,
  },
  sessionTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  sessionMeta: {
    color: '#a1a1aa',
    fontSize: 13,
  },
  emptyHourWrap: {
    height: 26,
    justifyContent: 'center',
    marginLeft: 2,
  },
  emptyHourDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#52525b',
  },
  adjustRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  adjustButton: {
    flexGrow: 1,
    minWidth: '47%',
    backgroundColor: '#111113',
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#27272a',
  },
  adjustButtonText: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
  },
  quickWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  quickChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#3f3f46',
    paddingVertical: 10,
    paddingHorizontal: 14,
    backgroundColor: '#18181b',
  },
  quickChipActive: {
    backgroundColor: '#e5e7eb',
    borderColor: '#d4d4d8',
  },
  quickChipText: {
    color: '#e4e4e7',
    fontWeight: '700',
  },
  quickChipTextActive: {
    color: '#09090b',
  },
  saveButton: {
    borderRadius: 24,
    paddingVertical: 18,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  saveButtonText: {
    color: '#09090b',
    fontSize: 17,
    fontWeight: '800',
  },
  floatingBarWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 80,
    zIndex: 50,
    elevation: 12,
  },
  floatingBar: {
    minHeight: 54,
    borderRadius: 22,
    paddingHorizontal: 16,
    backgroundColor: '#111113',
    borderWidth: 1,
    borderColor: '#3f3f46',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 8 },
    elevation: 12,
  },
  floatingBarText: {
    color: '#fafafa',
    fontSize: 15,
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
  },
  modalDismissArea: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: '#111113',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 30,
    borderTopWidth: 1,
    borderColor: '#3f3f46',
    gap: 18,
  },
  modalHandle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#52525b',
  },
  modalTitle: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '800',
  },
  modalSubtitle: {
    color: '#a1a1aa',
    fontSize: 14,
    lineHeight: 20,
  },
  modalCounterCard: {
    backgroundColor: '#18181b',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#3f3f46',
    alignItems: 'center',
    gap: 6,
  },
  modalCounterValue: {
    color: '#f8fafc',
    fontSize: 34,
    fontWeight: '800',
  },
  modalCounterMeta: {
    color: '#a1a1aa',
    fontSize: 14,
    fontWeight: '600',
  },
});
