import { StyleSheet } from 'react-native';

import { AppColors } from '../../theme/palette';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loaderWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: {
      padding: 18,
      paddingBottom: 140,
      gap: 18,
    },
    title: {
      color: colors.textPrimary,
      fontSize: 34,
      lineHeight: 40,
      fontWeight: '800',
    },
    dateLabel: {
      color: colors.textMuted,
      fontSize: 16,
      fontWeight: '600',
      marginBottom: -8,
    },
    goalsCard: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 16,
    },
    goalsTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
    },
    goalsTextWrap: {
      flex: 1,
      gap: 10,
    },
    goalEyebrow: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    goalHeadline: {
      color: colors.textPrimary,
      fontSize: 22,
      fontWeight: '800',
    },
    goalMeta: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    streakPill: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
    },
    streakText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '800',
    },
    milestonePill: {
      alignSelf: 'flex-start',
      borderRadius: 18,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 2,
    },
    milestoneTitle: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    milestoneText: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
    },
    reminderCard: {
      backgroundColor: colors.warning,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: colors.warningBorder,
      padding: 16,
      gap: 6,
    },
    reminderTitle: {
      color: colors.textPrimary,
      fontSize: 16,
      fontWeight: '800',
    },
    reminderText: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
    },
    statGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    card: {
      width: '48%',
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 8,
    },
    cardWide: {
      width: '100%',
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 8,
    },
    cardLabel: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    cardValue: {
      color: colors.textPrimary,
      fontSize: 28,
      fontWeight: '800',
    },
    cardMeta: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    insightsCard: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 14,
    },
    sectionTitle: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: '700',
    },
    sectionSubtitle: {
      color: colors.textMuted,
      fontSize: 14,
    },
    sectionTextWrap: {
      flex: 1,
      gap: 4,
    },
    insightGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    insightTile: {
      width: '48%',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 20,
      padding: 14,
      gap: 6,
    },
    insightTileWide: {
      width: '100%',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 20,
      padding: 14,
      gap: 6,
    },
    insightLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    insightValue: {
      color: colors.textPrimary,
      fontSize: 20,
      fontWeight: '800',
    },
    insightMeta: {
      color: colors.textSecondary,
      fontSize: 13,
      lineHeight: 18,
    },
    chartCard: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 16,
    },
    chartWrap: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
      minHeight: 180,
      gap: 10,
    },
    barColumn: {
      flex: 1,
      alignItems: 'center',
      gap: 8,
    },
    barTrack: {
      width: '100%',
      height: 120,
      backgroundColor: colors.surfaceAlt,
      borderRadius: 18,
      justifyContent: 'flex-end',
      overflow: 'hidden',
    },
    barFill: {
      width: '100%',
      backgroundColor: colors.accent,
      borderRadius: 18,
      minHeight: 6,
    },
    barLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
    },
    barMinutes: {
      color: colors.textSecondary,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
    },
    trendCard: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    trendRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 14,
    },
    trendBadge: {
      borderRadius: 999,
      paddingVertical: 8,
      paddingHorizontal: 12,
      backgroundColor: colors.surfaceAlt,
    },
    trendBadgePositive: {
      backgroundColor: colors.success,
    },
    trendBadgeNegative: {
      backgroundColor: colors.warning,
    },
    trendBadgeText: {
      color: colors.textPrimary,
      fontSize: 13,
      fontWeight: '800',
    },
    trendMeta: {
      color: colors.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      flex: 1,
    },
    sparklineRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      gap: 6,
      minHeight: 56,
    },
    sparklineBar: {
      flex: 1,
      borderRadius: 999,
      backgroundColor: colors.accentMuted,
      minHeight: 6,
    },
    heatmapCard: {
      backgroundColor: colors.surface,
      borderRadius: 28,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 14,
    },
    heatmapHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
    },
    heatmapMonthNav: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    heatmapMonthButton: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: colors.actionSurface,
      borderWidth: 1,
      borderColor: colors.actionBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heatmapMonthButtonDisabled: {
      opacity: 0.45,
    },
    heatmapMonthBadge: {
      minHeight: 34,
      borderRadius: 17,
      paddingHorizontal: 12,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heatmapMonthText: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
    heatmapWeekdayRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    heatmapWeekdayLabel: {
      width: '13.2%',
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    heatmapGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 6,
    },
    heatmapCell: {
      width: '13.2%',
      aspectRatio: 1,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 8,
      borderWidth: 2,
      borderColor: 'transparent',
      overflow: 'visible',
    },
    heatmapCellContent: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    heatmapCellToday: {
      borderColor: colors.textPrimary,
    },
    heatmapCellSelected: {
      borderColor: colors.accent,
      borderWidth: 2,
    },
    heatmapTooltip: {
      position: 'absolute',
      bottom: '100%',
      marginBottom: 10,
      minWidth: 54,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: colors.textPrimary,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 5,
    },
    heatmapTooltipText: {
      color: colors.background,
      fontSize: 11,
      fontWeight: '800',
    },
    heatmapCellEmpty: {
      backgroundColor: 'transparent',
      borderColor: 'transparent',
    },
    heatmapLabel: {
      color: colors.textMuted,
      fontSize: 13,
      lineHeight: 12,
      fontWeight: '700',
      textAlign: 'center',
      textAlignVertical: 'center',
      includeFontPadding: false,
      paddingVertical: 0,
      paddingBottom: 0,
    },
    heatmapLabelActive: {
      color: colors.textPrimary,
    },
    heatmapLegendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    heatmapLegendText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
    },
    heatmapLegendScale: {
      flexDirection: 'row',
      gap: 6,
    },
    heatmapLegendSwatch: {
      width: 14,
      height: 14,
      borderRadius: 4,
    },
  });
